config/routes.rb
Rails.application.routes.draw do

  root 'bocabulary#index'
  resources :quiz
  resources :bocabulary

  namespace :api, format: 'json' do
    namespace :v1  do
      resources :quiz
    end
  end

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 
  # devise_scope :user do
  #   post "sign_up", :to => "users/registrations#create"
  # #   get "sign_in", :to => "users/sessions#new"
  # end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :question_similars, dependent: :destroy
  scope :old, -> { order(created_at: :asc) }
  accepts_nested_attributes_for :question_similars
end

app/models/question_similar.rb
class QuestionSimilar < ApplicationRecord
  belongs_to :question, inverse_of: :question_similars
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        #  :authentication_keys [:name]

  def email_required?
    false
  end

  def email_changed?
    false
  end

  def will_save_change_to_email?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:name, :password) }
end

app/controllers/bocabulary_controller.rb
class BocabularyController < ApplicationController
  before_action :authenticate_user!

  def new
  end

  def index
  end

  def show
    @question = Question.new
    2.times { @question.question_similars.build}
    @question.question_similars.build
    @q = Question.ransack(params[:q])
    @questions = @q.result(distinct: true).old
    @question_similars = QuestionSimilar.all
  end

  def create
    binding.pry
    Question.create(create_params)
    redirect_to "/bocabulary/:#{current_user.id}"
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    @question.update(update_params)
    redirect_to "/bocabulary/#{current_user.id}"
  end

  def destroy
    question = Question.find(params[:id])
    question.destroy
    redirect_to "/bocabulary/:#{current_user.id}"
  end

  private

  def create_params
    params.require(:question).permit(:question, :discription, question_similars_attributes:[:similar_word])
  end

  def update_params
    params.require(:question).permit(:question, :discription)
  end

end

app/controllers/quiz_controller.rb
class QuizController < ApplicationController

  def show

    @questions  = Question.order("RANDOM()").sample(10)
    # @question = Question.discription.order("RANDOM()").limit(3)
    # session[:score] = nil
  end

  def index
    @questions  = Question.order("RANDOM()").sample(10)
    @wrong_question1 = Question.order("RANDOM()").sample(10)
    @wrong_question2 = Question.order("RANDOM()").sample(10)
    # render json: { data: @questions }
  end

  def create
    binding.pry
    # if params[:answer] == params[:orig]
    #   session[:score] += 1
    # end
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    # super
  end

  # POST /resource
  def create
    # super
    User.create(sign_up_params)
    redirect_to :root
  end

  # GET /resource/edit
  def edit
    # super
  end

  # PUT /resource
  def update
    # super
  end

  # DELETE /resource
  def destroy
    # super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  private

  def sign_up_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    # super
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bocabulary_helper.rb
module BocabularyHelper
end

app/helpers/quiz_helper.rb
module QuizHelper
end

app/views/bocabulary/create.html.erb
<div class="container">
  <h1 class="title">単語新規作成</h1>
  <p class="subtitle">下記のメニューからお選びください</p>
  <!-- <a class='' href="">新規ユーザー作成</a　class >
  <a class='' href="">単語帳</a>
  <a class='' href="">ランキング</a>
  <a class='' href="">単語マスタメンテナンス</a> -->
  <ul class="title_menu">
    <li>
      <%= link_to '新規作成', bocabulary_index_path, method: :post %>
    </li>
    <li>
      <%= link_to '単語編集', bocabulary_path, method: :delete %>
    </li>
    <li>
      <%= link_to '単語削除', edit_bocabulary_path  %>
    </li>
  </ul>

  <%= link_to 'トップに戻る', root_path %>


</div>

app/views/bocabulary/destroy.html.erb
<div class="container">
  <h1 class="title">単語削除</h1>
  <p class="subtitle">下記のメニューからお選びください</p>
  <!-- <a class='' href="">新規ユーザー作成</a　class >
  <a class='' href="">単語帳</a>
  <a class='' href="">ランキング</a>
  <a class='' href="">単語マスタメンテナンス</a> -->
  <ul class="title_menu">
    <li>
      <%= link_to '新規作成', bocabulary_index_path, method: :post %>
    </li>
    <li>
      <%= link_to '単語編集', bocabulary_path, method: :delete %>
    </li>
    <li>
      <%= link_to '単語削除', edit_bocabulary_path  %>
    </li>
  </ul>

  <%= link_to 'トップに戻る', root_path %>


</div>

app/views/bocabulary/edit.html.erb
<div class="container">
  <div class="modal-header">
    <h5 class="modal-title" id="exampleModalLongTitle">単語を修正</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <!-- <span aria-hidden="true">&times;</span> -->
    </button>
  </div>
  <div class="modal-body" style="margin: 3em;">
    <%= form_for @question, url: "/bocabulary/#{@question.id}", html: { class: "form-inline" } do |f| %>
      <%=  f.text_field :question, class:'form-control', placeholder: "単語"%>
      <%=  f.text_field :discription, class:'form-control', placeholder: "単語の意味"%>
      <%= f.submit "変更を保存する", class: "btn btn-primary" %>
    <% end %>
  </div>
  <div class="modal-footer">
    <%= link_to '閉じる', "/bocabulary/:#{current_user.id}" , class: "btn btn-secondary", data: {dismiss: "modal"} %>
  </div>
</div>

app/views/bocabulary/index.html.erb
<div class="container">
  <h1 class="title">Main menu</h1>
  <p class="subtitle">下記のメニューよりクリックしてください</p>
  <ul class="title_menu">
    <li>
      <%= link_to 'トップページ',  root_path %>
    </li>
    <li>
      <%= link_to '単語クイズ',  quiz_index_path %>
    </li>
    <li>
      <%= link_to 'ランキング',  root_path %>
    </li>
    <li>
      <%= link_to '単語マスタメンテナンス', "/bocabulary/#{current_user.id}" %>
    </li>
  </ul>

  <% if user_signed_in? %>
    <p><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></p>
  <% end %>
</div>

app/views/bocabulary/show.html.erb
<div class="container">
  <h1 class="title">単語マスタメンテナンス</h1>
  <p class="subtitle" style="margin-top: 3em;  margin-bottom: 3em;"> 新規作成 </p>
  <%= form_with model: @question, url: bocabulary_index_path, html: { class: "form-inline" } do |f| %>
  <div class="form-row">
    <%=  f.text_field :question, class:'form-control', placeholder: "単語"%>
    <%=  f.text_field :discription, class:'form-control', placeholder: "単語の意味"%>
  </div>
      <%= f.fields_for :question_similars do |question_similar| %>
        <%= question_similar.text_field :similar_word, class:'form-control', placeholder: "類似語" %>
      <% end %>
    <%=  f.submit "登録", class: "btn btn-primary" %>
  <% end %>
  <%= search_form_for @q, url: bocabulary_path, html: { class: "form-inline"} do |f| %>
    <%=  f.search_field :question_cont, class:'form-control', placeholder: "単語の検索" %>
    <%=  f.submit "検索", class: "btn btn-primary" %>
  <% end %>
  <p class="subtitle" style="margin-top: 3em;"> 単語一覧 </p>
  <% @questions.each.with_index(1) do |question, idx| %>
    <div class="card" style="margin: 5rem;">
      <div class="card-header">
        <p class="" >No.<%= idx %></p>
      </div>
      <div class="card-body">
        <h5 class="card-title"><%= question.question %></h5>
        <p class="card-text"><%= question.discription %></p>

          <div class="btn-group">
            <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              類義語
            </button>
            <div class="dropdown-menu">
            <ul class="list-group">
              <% question.question_similars.each do |similar| %>
                <li class="dropdown-item list-group-item" style="margin: 1em;"><%= similar.similar_word %></li>
              <% end %>
            </ul>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#"></a>
            </div>
          </div>

        <!-- <%= link_to '編集', "/bocabulary/#{question.id}/edit", class: "btn btn-primary", data: { toggle: 'modal', target: '#exampleModalCenter'} %> -->
        <%= link_to '編集', "/bocabulary/#{question.id}/edit", class: "btn btn-primary"%>
        <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <!-------------------------
                モーダルの中（edit.html.erb）
              -------------------------->
            </div>
          </div>
        </div>

        <%= link_to '削除', "/bocabulary/#{question.id}" , class: "btn btn-primary",
        data: { confirm: 'Are you sure?', method: 'delete', toggle: 'modal', target: '#exampleModalCenter'}%>
      </div>
    </div>
  <%end%>
  <%= link_to 'トップに戻る', root_path %>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vocabulary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.9.1/underscore.js" integrity="sha256-O4179En8zabOlPYBNvGp8cF0uh0vnSZpW4Q6Ul1h+8c=" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/quiz/index.html.erb
<div class="container">
  <h1 class="title">単語クイズ</h1>
  <p class="subtitle" style="margin-top: 3em;  margin-bottom: 3em;"> 正しい単語の意味を選んでね </p>
  <%= react_component("Quiz", { questions: [@questions, @wrong_question1, @wrong_question2]}) %>
  <%= link_to 'トップに戻る', root_path, class: "btn" %>
  <% if user_signed_in? %>
    <p><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn" %></p>
  <% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログイン", new_user_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "新規登録", new_user_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "パスワード忘れた方?", new_user_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_user_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_user_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>